### ISSUE TITLE
Could not execute skill because the Web Api request failed - Enrichment.AzureOpenAIEmbeddingSkill.#2

### ISSUE THREAD

**Issue by sindre-bouvet** [Azure/azure-search-vector-samples#228]
I am trying to run the notebook azure-search-integrated-vectorization-sample.ipynb, but when I run the code under "Create an indexer" I get the error message:

```
Web Api response status: 'NotFound', Web Api response details: '{"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}'
```

Everything before "Create an indexer" is running fine - the data source is created, the Index (under Indexes) is created, and the skillsets are created (under Skillsets), but under "Indexers" I get "Status = Failed", with the aforementioned error message. 

All of the keys and ids are correct, and the models are deployed as they should.

I have made sure that I use the azure-search-documents==11.6.0b1.

**Comment by mattgotteiner** [comment]
This error is frequently encountered when the Azure OpenAI deployment is not found. There are a couple of common reasons for this issue:

1. Different deployment and model name. Azure OpenAI allows you to name the deployment differently from the model. Be sure to use the deployment name and not the model name when setting up your skillset / indexer
2. No access using your credentials. If you are using user-assigned or system-assigned identity, be sure to give the identity "Cognitive Services User" permission to the Azure OpenAI account, otherwise it won't have access. If you are using API keys, make sure the key is correct
3.

**Comment by ahmedsza** [comment]
I am getting the exact same error. I have check the API keys , model names a few times.. @sindre-bouvet  - how did you solve it?

**Comment by ahmedsza** [comment]
Sorry. Ignore.. I would recommend one little change. The env file has this
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_ID=text-ada-embedding-002
The model name and deployment name I have is text-embedding-ada-002 (i,e deployment name=model name)

Took me awhile to figure out it was different!
